---
version: '2.1'
services:
  nginx:
    image: czerasz/http-debugger

  base:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ".:/conf"
    command:
      - "-c"
      - "/conf/nginx-test.conf"
    links:
      - nginx
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
